version: '3.9'
services:
  metabase-meetup:
    image: metabase/metabase:v0.45.3
    container_name: metabase-meetup
    hostname: metabase-meetup
    volumes:
      - metabase-meetup/metabase.db:/metabase.db
    ports:
      - 3001:3000
    networks:
      - net-meta-meetup
  postgres-meetup:
    image: postgres:15.1
    container_name: postgres-meetup
    hostname: postgres
    volumes:
      - postgre-meetup:/var/lib/postgresql/data
    ports:
      - 5442:5432
    environment:
      POSTGRES_PASSWORD: to_modify
    networks:
      - net-meta-meetup
  nginx-dev:
    image: nginx:1.23.3
    container_name: nginx-meetup
    hostname: nginx-meetup
    volumes:
      - ./config:/usr/share/nginx/html:ro
    ports:
      - 8081:80
    networks:
      - net-meta-meetup
networks:
  net-meta-meetup:
    driver: bridge